apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metallb-charts.yaml
  - oauth2-proxy-charts.yaml
  - metrics-server-charts.yaml
  - nfs-subdir-external-provisioner-charts.yaml
  - node-feature-discovery-charts.yaml
  - stakater-charts.yaml


